import { defineEventHandler, createError, setResponseHeader } from 'h3';
import { getFirestore } from 'firebase-admin/firestore';
import archiver from 'archiver';
import { PassThrough } from 'stream';

export default defineEventHandler(async (event) => {
  try {
    // Check if user is authenticated and is an admin
    const user = event.context.user;
    if (!user || user.role !== 'admin') {
      throw createError({
        statusCode: 403,
        statusMessage: 'Forbidden: Only admins can backup Firestore data'
      });
    }

    const body = await readBody(event);
    const { collections = [] } = body;

    const timestamp = new Date().toISOString().replace(/:/g, '-').replace(/\./g, '-');
    const zipFilename = `firestore_backup_${timestamp}.zip`;

    // Create a pass-through stream that will hold our zip data
    const passThrough = new PassThrough();

    // Create an archiver instance linked to the pass-through stream
    const archive = archiver('zip', {
      zlib: { level: 9 } // Maximum compression
    });

    // Pipe the archive data to the pass-through stream
    archive.pipe(passThrough);

    // Add a README file to the archive
    const readmeContent = `Firestore Backup
Timestamp: ${timestamp}
Generated by: ${user.email || user.username || 'Admin'}
Date: ${new Date().toLocaleString()}
`;

    archive.append(readmeContent, { name: 'README.txt' });

    const db = getFirestore();

    // Get all collections if none specified
    let collectionsToBackup = collections;
    if (collections.length === 0) {
      const collectionsRef = await db.listCollections();
      collectionsToBackup = collectionsRef.map(col => col.id);
    }

    // Backup each collection
    for (const collectionName of collectionsToBackup) {
      try {
        const collectionRef = db.collection(collectionName);
        const snapshot = await collectionRef.get();

        if (snapshot.empty) {
          // Add an empty collection marker
          archive.append(JSON.stringify([]), { name: `${collectionName}.json` });
          continue;
        }

        // Process documents
        const documents = [];
        snapshot.forEach(doc => {
          const data = doc.data();

          // Convert Firestore Timestamps to ISO strings
          const processedData = {};
          Object.keys(data).forEach(key => {
            const value = data[key];
            if (value && typeof value === 'object' && value.constructor && value.constructor.name === 'Timestamp') {
              processedData[key] = value.toDate().toISOString();
            } else {
              processedData[key] = value;
            }
          });

          documents.push({
            id: doc.id,
            ...processedData
          });
        });

        // Add the collection data to the archive
        archive.append(JSON.stringify(documents, null, 2), { name: `${collectionName}.json` });
      } catch (err) {
        console.error(`Error backing up collection ${collectionName}:`, err);
        // Add an error note for this collection
        archive.append(JSON.stringify({ error: err.message }), { name: `${collectionName}_ERROR.json` });
      }
    }

    // Finalize the archive
    await archive.finalize();

    // Set response headers for download
    setResponseHeader(event, 'Content-Type', 'application/zip');
    setResponseHeader(event, 'Content-Disposition', `attachment; filename="${zipFilename}"`);

    // Return the stream as the response
    return passThrough;
  } catch (error) {
    console.error('Firestore backup error:', error);
    throw createError({
      statusCode: 500,
      statusMessage: 'Failed to backup Firestore database',
      data: error
    });
  }
});
