import { defineEventHandler, createError, setResponseHeader } from 'h3';
import mongoose from 'mongoose';
import archiver from 'archiver';
import { Readable } from 'stream';
import { PassThrough } from 'stream';

export default defineEventHandler(async (event) => {
  try {
    // Check if user is authenticated and is an admin
    const user = event.context.user;
    if (!user || user.role !== 'admin') {
      throw createError({
        statusCode: 403,
        statusMessage: 'Forbidden: Only admins can backup the database'
      });
    }

    const body = await readBody(event);
    const { models = [] } = body;

    const timestamp = new Date().toISOString().replace(/:/g, '-').replace(/\./g, '-');
    const zipFilename = `mongodb_backup_${timestamp}.zip`;

    // Create a pass-through stream that will hold our zip data
    const passThrough = new PassThrough();

    // Create an archiver instance linked to the pass-through stream
    const archive = archiver('zip', {
      zlib: { level: 9 } // Maximum compression
    });

    // Pipe the archive data to the pass-through stream
    archive.pipe(passThrough);

    // Add a README file to the archive
    const readmeContent = `MongoDB Backup
Timestamp: ${timestamp}
Generated by: ${user.email || user.username || 'Admin'}
Date: ${new Date().toLocaleString()}
`;

    archive.append(readmeContent, { name: 'README.txt' });

    // Get MongoDB connection info
    const connectionString = mongoose.connection.client.s.url;

    if (models.length > 0) {
      // Backup specific models
      for (const modelName of models) {
        if (!mongoose.modelNames().includes(modelName)) {
          continue; // Skip if model doesn't exist
        }

        const model = mongoose.model(modelName);
        const documents = await model.find().lean();

        // Add the model data to the archive
        archive.append(JSON.stringify(documents, null, 2), { name: `${modelName}.json` });
      }
    } else {
      // Backup all models
      for (const modelName of mongoose.modelNames()) {
        const model = mongoose.model(modelName);
        const documents = await model.find().lean();

        // Add the model data to the archive
        archive.append(JSON.stringify(documents, null, 2), { name: `${modelName}.json` });
      }
    }

    // Finalize the archive
    await archive.finalize();

    // Set response headers for download
    setResponseHeader(event, 'Content-Type', 'application/zip');
    setResponseHeader(event, 'Content-Disposition', `attachment; filename="${zipFilename}"`);

    // Return the stream as the response
    return passThrough;
  } catch (error) {
    console.error('Database backup error:', error);
    throw createError({
      statusCode: 500,
      statusMessage: 'Failed to backup database',
      data: error
    });
  }
});
